// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/openmomentso/momentso/pkg/database/db"
)

type CreateProjectInput struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type CreateProjectPayload struct {
	Project db.Project `json:"project"`
}

type CreateTimeEntryInput struct {
	Description string     `json:"description"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
}

type CreateTimeEntryPayload struct {
	TimeEntry db.TimeEntry `json:"timeEntry"`
}

type ProjectConnection struct {
	Edges []db.Project `json:"edges"`
}

type SignInPayload struct {
	Token string  `json:"token"`
	User  db.User `json:"user"`
}

type SignUpPayload struct {
	Token string  `json:"token"`
	User  db.User `json:"user"`
}

type TimeEntryConnection struct {
	Edges []db.TimeEntry `json:"edges"`
}

type UpdateProjectPayload struct {
	Project db.Project `json:"project"`
}

type UpdateTimeEntryPayload struct {
	TimeEntry db.TimeEntry `json:"timeEntry"`
}
