// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateTimeEntryInput struct {
	StartedAt   *time.Time `json:"startedAt,omitempty"`
	Description *string    `json:"description,omitempty"`
}
