// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        int64     `db:"id"`
	UserID    int64     `db:"user_id"`
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}

type Project struct {
	ID        int64       `db:"id"`
	UserID    int64       `db:"user_id"`
	CreatedAt time.Time   `db:"created_at"`
	Name      string      `db:"name"`
	Color     string      `db:"color"`
	ClientID  pgtype.Int8 `db:"client_id"`
}

type Session struct {
	ID        int64     `db:"id"`
	UserID    int64     `db:"user_id"`
	Token     string    `db:"token"`
	CreatedAt time.Time `db:"created_at"`
}

type TimeEntry struct {
	ID          int64              `db:"id"`
	Description string             `db:"description"`
	CreatedBy   int64              `db:"created_by"`
	CreatedAt   time.Time          `db:"created_at"`
	StartedAt   time.Time          `db:"started_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at"`
	ProjectID   pgtype.Int8        `db:"project_id"`
}

type User struct {
	ID        int64     `db:"id"`
	Email     string    `db:"email"`
	Password  string    `db:"password"`
	CreatedAt time.Time `db:"created_at"`
}
