// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID          int64       `db:"id"`
	Name        string      `db:"name"`
	WorkspaceID pgtype.Int8 `db:"workspace_id"`
	CreatedAt   time.Time   `db:"created_at"`
}

type Project struct {
	ID          int64       `db:"id"`
	Name        string      `db:"name"`
	Color       string      `db:"color"`
	ClientID    pgtype.Int8 `db:"client_id"`
	WorkspaceID pgtype.Int8 `db:"workspace_id"`
	CreatedAt   time.Time   `db:"created_at"`
}

type Session struct {
	ID        int64     `db:"id"`
	UserID    int64     `db:"user_id"`
	Token     string    `db:"token"`
	CreatedAt time.Time `db:"created_at"`
}

type TimeEntry struct {
	ID          int64              `db:"id"`
	Description string             `db:"description"`
	WorkspaceID pgtype.Int8        `db:"workspace_id"`
	CreatedBy   int64              `db:"created_by"`
	CreatedAt   time.Time          `db:"created_at"`
	StartedAt   time.Time          `db:"started_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at"`
}

type User struct {
	ID          int64       `db:"id"`
	Email       string      `db:"email"`
	Password    string      `db:"password"`
	WorkspaceID pgtype.Int8 `db:"workspace_id"`
	CreatedAt   time.Time   `db:"created_at"`
}

type Workspace struct {
	ID        int64     `db:"id"`
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
}
