// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID          int64
	Name        string
	WorkspaceID sql.NullInt64
	CreatedAt   time.Time
}

type Project struct {
	ID          int64
	Name        string
	Color       string
	ClientID    sql.NullInt64
	WorkspaceID sql.NullInt64
	CreatedAt   time.Time
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt time.Time
}

type TimeEntry struct {
	ID          int64
	Description string
	WorkspaceID sql.NullInt64
	CreatedBy   sql.NullInt64
	CreatedAt   time.Time
	StartedAt   time.Time
	CompletedAt sql.NullTime
}

type User struct {
	ID          int64
	Email       string
	Password    string
	WorkspaceID sql.NullInt64
	CreatedAt   time.Time
}

type Workspace struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}
