package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/openmomentso/momentso/pkg/app/auth"
	"github.com/openmomentso/momentso/pkg/database/db"
)

// Email is the resolver for the email field.
func (r *userResolver) Email(ctx context.Context, obj *db.User) (string, error) {
	user, _ := auth.UserForCtx(ctx)
	if user.ID != obj.ID {
		return "", fmt.Errorf("unauthorized")
	}

	return user.Email, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
